apiVersion: v1
kind: Pod
metadata:
  name: jumpbox
  namespace: default
spec:
  containers:
    - name: jumpbox
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
      tty: true
      stdin: true
  restartPolicy: Never
