apiVersion: apps/v1
kind: Deployment
metadata:
  name: potter-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potter-shell
  template:
    metadata:
      labels:
        app: potter-shell
    spec:
      containers:
        - name: shell
          image: alpine
          command: [ "sh", "-c", "sleep 3600" ]
          stdin: true
          tty: true
