apiVersion: v1
kind: Pod
metadata:
  name: potter
spec:
  containers:
    - name: shell
      image: alpine
      command: ["sh", "-c", "apk add curl; curl http://potter-maga.brazilsouth.cloudapp.azure.com:8080" ]
  restartPolicy: Never
