apiVersion: batch/v1
kind: Job
metadata:
  name: potter-v3
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: shell
          image: alpine
          command: ["sh"]
          stdin:true
          tty:true
